name: spend_time
description: A new Stopwatch app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Bloc
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # Config
  logger: ^1.3.0

  # DB
  sqflite: ^2.2.6
  sqfentity: ^2.3.0+5
  sqfentity_gen: ^2.3.0+4
  shared_preferences: ^2.1.0

  # Design
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
  carousel_slider: ^4.2.1

  # Localization
  easy_localization: ^3.0.1

  # Util
  http: ^0.13.5
  device_info_plus: ^8.2.0
  package_info_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400